export interface TeamInfo {
  id: string;
  name: string;
  shortName: string;
  sport: 'SOCCER' | 'BASKETBALL' | 'TENNIS';
  league: string;
  flag: string;
  logo: string;
  stadium: string;
  capacity: string;
  founded: number;
  manager: string;
  starPlayer: string;
  recentForm: ('W' | 'D' | 'L')[];
  winRatePercent: number;
  attackRating: number;
  defenseRating: number;
  nextMatch: string;
}

export const TEAMS_DATABASE: TeamInfo[] = [
  {
    id: 't-arsenal',
    name: 'Arsenal FC',
    shortName: 'ARS',
    sport: 'SOCCER',
    league: 'Premier League',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    logo: '🔴',
    stadium: 'Emirates Stadium',
    capacity: '60,704',
    founded: 1886,
    manager: 'Mikel Arteta',
    starPlayer: 'Bukayo Saka',
    recentForm: ['W', 'W', 'D', 'W', 'W'],
    winRatePercent: 78.5,
    attackRating: 2.15,
    defenseRating: 0.75,
    nextMatch: 'vs Chelsea (Today, 74\')',
  },
  {
    id: 't-chelsea',
    name: 'Chelsea FC',
    shortName: 'CHE',
    sport: 'SOCCER',
    league: 'Premier League',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    logo: '🔵',
    stadium: 'Stamford Bridge',
    capacity: '40,341',
    founded: 1905,
    manager: 'Enzo Maresca',
    starPlayer: 'Cole Palmer',
    recentForm: ['W', 'L', 'D', 'W', 'L'],
    winRatePercent: 58.0,
    attackRating: 1.45,
    defenseRating: 1.30,
    nextMatch: 'vs Arsenal (Today, 74\')',
  },
  {
    id: 't-realmadrid',
    name: 'Real Madrid CF',
    shortName: 'RMA',
    sport: 'SOCCER',
    league: 'La Liga',
    flag: '🇪🇸',
    logo: '⚪',
    stadium: 'Santiago Bernabéu',
    capacity: '81,044',
    founded: 1902,
    manager: 'Carlo Ancelotti',
    starPlayer: 'Kylian Mbappé',
    recentForm: ['W', 'W', 'W', 'D', 'W'],
    winRatePercent: 84.0,
    attackRating: 2.30,
    defenseRating: 0.85,
    nextMatch: 'vs Bayern Munich (Today, 20:00)',
  },
  {
    id: 't-bayern',
    name: 'FC Bayern Munich',
    shortName: 'BAY',
    sport: 'SOCCER',
    league: 'Bundesliga',
    flag: '🇩🇪',
    logo: '🔴',
    stadium: 'Allianz Arena',
    capacity: '75,024',
    founded: 1900,
    manager: 'Vincent Kompany',
    starPlayer: 'Harry Kane',
    recentForm: ['W', 'W', 'L', 'W', 'W'],
    winRatePercent: 76.0,
    attackRating: 2.10,
    defenseRating: 1.10,
    nextMatch: 'vs Real Madrid (Today, 20:00)',
  },
  {
    id: 't-enyimba',
    name: 'Enyimba International FC',
    shortName: 'ENY',
    sport: 'SOCCER',
    league: 'NPFL Nigeria',
    flag: '🇳🇬',
    logo: '🔵',
    stadium: 'Enyimba International Stadium',
    capacity: '16,000',
    founded: 1976,
    manager: 'Yemi Olanrewaju',
    starPlayer: 'Joseph Atule',
    recentForm: ['W', 'W', 'D', 'W', 'W'],
    winRatePercent: 80.0,
    attackRating: 1.80,
    defenseRating: 0.50,
    nextMatch: 'vs Kano Pillars (Today, 58\')',
  },
  {
    id: 't-celtics',
    name: 'Boston Celtics',
    shortName: 'BOS',
    sport: 'BASKETBALL',
    league: 'NBA Basketball',
    flag: '🇺🇸',
    logo: '☘️',
    stadium: 'TD Garden',
    capacity: '19,156',
    founded: 1946,
    manager: 'Joe Mazzulla',
    starPlayer: 'Jayson Tatum',
    recentForm: ['W', 'W', 'W', 'L', 'W'],
    winRatePercent: 82.0,
    attackRating: 2.40,
    defenseRating: 0.80,
    nextMatch: 'vs LA Lakers (Live Q3)',
  },
  {
    id: 't-alcaraz',
    name: 'Carlos Alcaraz',
    shortName: 'ALC',
    sport: 'TENNIS',
    league: 'ATP Tour',
    flag: '🇪🇸',
    logo: '🎾',
    stadium: 'Grand Slam Courts',
    capacity: '15,000',
    founded: 2003,
    manager: 'Juan Carlos Ferrero',
    starPlayer: 'Carlos Alcaraz',
    recentForm: ['W', 'W', 'W', 'W', 'W'],
    winRatePercent: 89.0,
    attackRating: 2.20,
    defenseRating: 0.80,
    nextMatch: 'vs Jannik Sinner (Live Set 3)',
  },
];
