/**
 * MIVAJ SPORTS TELEGRAM VIP PRIVATE DISPATCH ENGINE
 * Generates elite, 1-way confidential system transmissions (not a conversational bot).
 * Welcomes new channel members, recognizes returning users, and delivers time-aware VIP FOMO dispatches.
 */

export interface TelegramVipUser {
  telegramId: number | string;
  firstName?: string;
  username?: string;
  timezone?: string; // e.g. "Africa/Lagos", "UTC"
  joinedAt: string;
  lastSeenAt: string;
  referralCode?: string;
  visitsCount: number;
}

export class TelegramVipDispatcher {
  /**
   * Generates a time-aware greeting based on the user's timezone or WAT (UTC+1)
   */
  public static getTimeAwareGreeting(timezone = 'Africa/Lagos'): { greeting: string; period: string; icon: string } {
    try {
      const formatter = new Intl.DateTimeFormat('en-US', {
        hour: 'numeric',
        hour12: false,
        timeZone: timezone,
      });
      const hour = parseInt(formatter.format(new Date()), 10);

      if (hour >= 5 && hour < 12) {
        return { greeting: 'Good morning', period: 'MORNING DISPATCH', icon: '☀️' };
      } else if (hour >= 12 && hour < 17) {
        return { greeting: 'Good afternoon', period: 'MIDDAY TACTICAL WIRE', icon: '⚡' };
      } else if (hour >= 17 && hour < 22) {
        return { greeting: 'Good evening', period: 'PRIME TIME INTEL', icon: '🌆' };
      } else {
        return { greeting: 'Night session active', period: 'LATE NIGHT RADAR', icon: '🌙' };
      }
    } catch {
      return { greeting: 'Welcome', period: 'SYSTEM DISPATCH', icon: '⚡' };
    }
  }

  /**
   * Generates the Spectacular 1-Way VIP Welcome Transmission
   */
  public static buildVipWelcomeMessage(params: {
    name: string;
    username?: string;
    isReturning?: boolean;
    referralCode?: string;
    topBankers?: Array<{ match: string; pick: string; odds: number; winProb: number }>;
  }): string {
    const { name, isReturning, referralCode, topBankers } = params;
    const timeInfo = this.getTimeAwareGreeting();
    const cleanRef = referralCode ? `?ref=${referralCode.replace(/^@/, '')}` : '';
    const portalUrl = `https://mivaj.com${cleanRef}`;

    const bankerSection = topBankers && topBankers.length > 0
      ? topBankers.map((b, i) => `  ${i + 1}. ${b.match}\n     🎯 Pick: <b>${b.pick}</b> @ ${b.odds} (${b.winProb}% Win Prob)`).join('\n\n')
      : `  1. RB Leipzig vs Gladbach • <b>1X</b> @ 1.13 (95% Poisson Prob)\n  2. Bournemouth vs Everton • <b>1X</b> @ 1.14 (95% Poisson Prob)\n  3. Union Berlin vs Frankfurt • <b>1X</b> @ 1.14 (94% Poisson Prob)`;

    if (isReturning) {
      return [
        `╔═══════════════════════════════════╗`,
        `  ⚡ <b>MIVAJ SPORTS CORE // VIP TERMINAL</b>`,
        `  SECURE ACCESS GRANTED: <b>${name.toUpperCase()}</b>`,
        `╚═══════════════════════════════════╝`,
        ``,
        `<i>[1-WAY CONFIDENTIAL TRANSMISSION // DO NOT REPLY]</i>`,
        ``,
        `${timeInfo.icon} <b>${timeInfo.greeting}, ${name}. Welcome back to the arena.</b>`,
        `📡 <b>Channel:</b> Mivaj VIP Quantitative Radar • <b>Latency:</b> 8ms`,
        ``,
        `📊 <b>LIVE SYSTEM RECONCILIATION:</b>`,
        `• <b>100% Audited Ledger:</b> All weekend referee score sheets settled.`,
        `• <b>Today's Dixon-Coles xG Engine:</b> 3 Ultra-Bankers active with 94%+ safety index.`,
        `• <b>Sub-Second Haptics:</b> Live goal tremors calibrated for your device.`,
        ``,
        `🔥 <b>ACTIVE BANKER SLIPS TODAY:</b>`,
        bankerSection,
        ``,
        `🚀 <b>INITIALIZE YOUR LIVE MATCH COMMAND CENTER:</b>`,
        `👉 <a href="${portalUrl}">${portalUrl}</a>`,
        ``,
        `<i>[SYSTEM DIRECTIVE: Tap the link above to view live pitch radar, sub-second scores & auto-settled tickets]</i>`
      ].join('\n');
    }

    // Spectacular First-Time VIP Induction
    return [
      `╔═══════════════════════════════════════╗`,
      `  👑 <b>MIVAJ SPORTS // VIP SYSTEM DIRECTIVE</b>`,
      `  CONFIDENTIAL PUNTER CLEARANCE #8821`,
      `╚═══════════════════════════════════════╝`,
      ``,
      `<i>[AUTOMATED 1-WAY STADIUM TERMINAL — DIRECT NOTIFICATION ONLY]</i>`,
      ``,
      `${timeInfo.icon} <b>${timeInfo.greeting}, ${name}.</b>`,
      `You have been issued priority spectator clearance into the <b>Mivaj Sports Live Match Core</b>.`,
      ``,
      `💎 <b>WHAT MAKES YOUR VIP ACCESS DIFFERENT:</b>`,
      `1. <b>Zero Fake Tips:</b> Every prediction is generated by our calibrated Dixon-Coles mathematical engine.`,
      `2. <b>Immutable Referee Ledger:</b> We never delete losses. 100% of matches are audited transparently.`,
      `3. <b>Sub-Meter Hyperlocal Radar:</b> Live pitch moisture, real-time xG power curves & ball trajectory.`,
      `4. <b>Instant Slip Settlement:</b> Placed bets auto-settle directly to your profile upon final whistle.`,
      ``,
      `🔥 <b>UNLOCKED TODAY'S PRIME SELECTIONS:</b>`,
      bankerSection,
      ``,
      `🎯 <b>ENTER YOUR PERSONAL VIP COCKPIT:</b>`,
      `👉 <a href="${portalUrl}">${portalUrl}</a>`,
      ``,
      `<i>⚠️ Note: This channel is a dedicated broadcast transmitter. Live match updates and goal alarms will be beamed to you here in real-time.</i>`,
      `<i>Ref ID: MIVAJ-${Date.now().toString(36).toUpperCase()} • 100% Encrypted</i>`
    ].join('\n');
  }

  /**
   * Generates periodic high-impact viral FOMO reminders for Telegram viewers
   */
  public static buildViralFomoReminder(type: 'KICKOFF_IMMINENT' | 'HALFTIME_SHIFT' | 'SETTLEMENT_RECORD'): string {
    const portalUrl = 'https://mivaj.com';

    if (type === 'KICKOFF_IMMINENT') {
      return [
        `⚡ <b>KICKOFF ALERT: HIGH-STAKES MATCHES COMMENCING</b>`,
        `----------------------------------------`,
        `The opening whistle blows in under 15 minutes across Europe's top leagues.`,
        ``,
        `📊 <b>Today's Algorithm Bank:</b>`,
        `Our model has identified a 95.2% win probability consensus on today's Double Chance & Over 1.5 markets.`,
        ``,
        `👉 <b>View Live Pitch Trajectory & Lock Your Slip:</b>`,
        `<a href="${portalUrl}">${portalUrl}</a>`,
        `<i>[Direct Transmission • Mivaj Match Engine]</i>`
      ].join('\n');
    }

    if (type === 'HALFTIME_SHIFT') {
      return [
        `🚨 <b>HALFTIME TACTICAL RE-CALIBRATION</b>`,
        `----------------------------------------`,
        `First-half expected goals (xG) metrics are deviating from live odds across 4 fixtures.`,
        ``,
        `💰 <b>Live Value Opportunity:</b>`,
        `Second-half momentum index indicates high probability second-half goals.`,
        ``,
        `👉 <b>Follow Live 2D Tactical Radar Now:</b>`,
        `<a href="${portalUrl}">${portalUrl}</a>`
      ].join('\n');
    }

    return [
      `📜 <b>OFFICIAL MATCHDAY SETTLEMENT NOTICE</b>`,
      `----------------------------------------`,
      `Referees have logged final scores into the immutable audit ledger.`,
      `All placed tickets for concluded matches are now officially settled.`,
      ``,
      `👉 <b>Check Your Win Slips & Aura Balance:</b>`,
      `<a href="${portalUrl}/dashboard">${portalUrl}/dashboard</a>`
    ].join('\n');
  }

  /**
   * Sends a private message directly to a Telegram User via Bot API
   */
  public static async sendPrivateVipMessage(botToken: string, chatId: number | string, text: string): Promise<boolean> {
    try {
      const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: chatId,
          text,
          parse_mode: 'HTML',
          disable_web_page_preview: false,
        }),
      });
      const data = await res.json();
      return !!data.ok;
    } catch {
      return false;
    }
  }
}
