/**
 * 20+ FREE OPEN-SOURCE APIS & ENGINES REGISTRY
 * 100% Free with zero API keys required and $0 operating cost forever.
 */

export interface FreeApiDefinition {
  id: number;
  name: string;
  category: 'SPORTS' | 'WEATHER' | 'CURRENCY' | 'GEOLOCATION' | 'NEWS' | 'MEDIA' | 'HARDWARE' | 'AUDIO';
  websiteUrl: string;
  endpointUrl: string;
  description: string;
  cost: '$0 Free';
}

export const TWENTY_FREE_APIS_REGISTRY: FreeApiDefinition[] = [
  {
    id: 1,
    name: 'TheSportsDB API',
    category: 'SPORTS',
    websiteUrl: 'https://www.thesportsdb.com',
    endpointUrl: 'https://www.thesportsdb.com/api/v1/json/3/searchteams.php',
    description: 'Free JSON API for team logos, stadium capacities, and manager metadata.',
    cost: '$0 Free',
  },
  {
    id: 2,
    name: 'Wikidata SPARQL Knowledge API',
    category: 'SPORTS',
    websiteUrl: 'https://www.wikidata.org',
    endpointUrl: 'https://query.wikidata.org/sparql',
    description: 'Open-source SPARQL endpoint for player birthdates, caps, and career honors.',
    cost: '$0 Free',
  },
  {
    id: 3,
    name: 'Football-Data.org Free Tier',
    category: 'SPORTS',
    websiteUrl: 'https://www.football-data.org',
    endpointUrl: 'https://api.football-data.org/v4/competitions',
    description: 'European league standings, fixtures, and top scorers.',
    cost: '$0 Free',
  },
  {
    id: 4,
    name: 'OpenLigaDB API',
    category: 'SPORTS',
    websiteUrl: 'https://www.openligadb.de',
    endpointUrl: 'https://api.openligadb.de/getmatchdata',
    description: 'Open-source European & German football match data API.',
    cost: '$0 Free',
  },
  {
    id: 5,
    name: 'Open-Meteo Weather API',
    category: 'WEATHER',
    websiteUrl: 'https://open-meteo.com',
    endpointUrl: 'https://api.open-meteo.com/v1/forecast',
    description: '100% free open-source stadium pitch weather forecast API (no key).',
    cost: '$0 Free',
  },
  {
    id: 6,
    name: 'Frankfurter ECB Currency API',
    category: 'CURRENCY',
    websiteUrl: 'https://frankfurter.dev',
    endpointUrl: 'https://api.frankfurter.dev/v1/latest',
    description: 'European Central Bank live currency exchange rates (no key).',
    cost: '$0 Free',
  },
  {
    id: 7,
    name: 'ExchangeRate-API Free Tier',
    category: 'CURRENCY',
    websiteUrl: 'https://www.exchangerate-api.com',
    endpointUrl: 'https://open.er-api.com/v6/latest/USD',
    description: 'Global fiat exchange rates feed for stake conversions.',
    cost: '$0 Free',
  },
  {
    id: 8,
    name: 'ip-api.com Geolocation API',
    category: 'GEOLOCATION',
    websiteUrl: 'https://ip-api.com',
    endpointUrl: 'http://ip-api.com/json',
    description: '100% free IP geolocation for auto-detecting user country & currency.',
    cost: '$0 Free',
  },
  {
    id: 9,
    name: 'ipapi.co Geolocation API',
    category: 'GEOLOCATION',
    websiteUrl: 'https://ipapi.co',
    endpointUrl: 'https://ipapi.co/json/',
    description: 'Secondary IP country and timezone detection provider.',
    cost: '$0 Free',
  },
  {
    id: 10,
    name: 'Google News RSS Feed Engine',
    category: 'NEWS',
    websiteUrl: 'https://news.google.com',
    endpointUrl: 'https://news.google.com/rss/search?q=football',
    description: 'Real-time breaking sports news XML feed converter.',
    cost: '$0 Free',
  },
  {
    id: 11,
    name: 'Sky Sports RSS Feed',
    category: 'NEWS',
    websiteUrl: 'https://www.skysports.com',
    endpointUrl: 'https://www.skysports.com/rss/12040',
    description: 'Live European football breaking headlines RSS feed.',
    cost: '$0 Free',
  },
  {
    id: 12,
    name: 'BBC Sport RSS Feed',
    category: 'NEWS',
    websiteUrl: 'https://www.bbc.com/sport',
    endpointUrl: 'http://feeds.bbci.co.uk/sport/rss.xml',
    description: 'Global multi-sport news RSS XML feed.',
    cost: '$0 Free',
  },
  {
    id: 13,
    name: 'ESPN News RSS Feed',
    category: 'NEWS',
    websiteUrl: 'https://www.espn.com',
    endpointUrl: 'https://www.espn.com/espn/rss/news',
    description: 'ESPN global breaking headlines RSS feed.',
    cost: '$0 Free',
  },
  {
    id: 14,
    name: 'Wikimedia Commons Open Images API',
    category: 'MEDIA',
    websiteUrl: 'https://commons.wikimedia.org',
    endpointUrl: 'https://commons.wikimedia.org/w/api.php',
    description: 'High-res open-license athlete & stadium photography API.',
    cost: '$0 Free',
  },
  {
    id: 15,
    name: 'OpenStreetMap Nominatim API',
    category: 'GEOLOCATION',
    websiteUrl: 'https://nominatim.openstreetmap.org',
    endpointUrl: 'https://nominatim.openstreetmap.org/search',
    description: 'Stadium GPS coordinates and city map geocoding engine.',
    cost: '$0 Free',
  },
  {
    id: 16,
    name: 'Web Speech Synthesis API',
    category: 'AUDIO',
    websiteUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis',
    endpointUrl: 'window.speechSynthesis',
    description: 'Browser-native live stadium commentator voice engine.',
    cost: '$0 Free',
  },
  {
    id: 17,
    name: 'Web Speech Recognition API',
    category: 'HARDWARE',
    websiteUrl: 'https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition',
    endpointUrl: 'webkitSpeechRecognition',
    description: 'Browser-native hands-free voice search engine.',
    cost: '$0 Free',
  },
  {
    id: 18,
    name: 'Screen Wake Lock API',
    category: 'HARDWARE',
    websiteUrl: 'https://w3c.github.io/screen-wake-lock/',
    endpointUrl: 'navigator.wakeLock',
    description: 'Prevents phone screen from going black during live matches.',
    cost: '$0 Free',
  },
  {
    id: 19,
    name: 'Web Audio API Crowd Synth Engine',
    category: 'AUDIO',
    websiteUrl: 'https://webaudio.github.io/web-audio-api/',
    endpointUrl: 'AudioContext',
    description: 'Synthesizes dynamic stadium crowd cheer roars ($0 bandwidth).',
    cost: '$0 Free',
  },
  {
    id: 20,
    name: 'Vibration Haptics API',
    category: 'HARDWARE',
    websiteUrl: 'https://w3c.github.io/vibration/',
    endpointUrl: 'navigator.vibrate',
    description: 'Tactile vibration feedback for goal alerts and bet slips.',
    cost: '$0 Free',
  },
  {
    id: 21,
    name: 'Web Share API',
    category: 'HARDWARE',
    websiteUrl: 'https://w3c.github.io/web-share/',
    endpointUrl: 'navigator.share',
    description: 'Native mobile share sheet integration (WhatsApp, Instagram).',
    cost: '$0 Free',
  },
  {
    id: 22,
    name: 'Canvas Confetti Engine',
    category: 'MEDIA',
    websiteUrl: 'https://github.com/catdad/canvas-confetti',
    endpointUrl: 'canvas-confetti',
    description: 'Browser particle rendering engine for goal celebrations.',
    cost: '$0 Free',
  },
];
