'use client';

import React from 'react';
import { ShieldCheck, Scale, AlertTriangle, ArrowLeft, CheckCircle2 } from 'lucide-react';
import Link from 'next/link';

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-void text-white p-4 sm:p-8 font-mono text-xs space-y-6">
      <div className="max-w-4xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-2xl bg-stadiumGreen text-black font-black text-xl shadow-lg">
              ⚖️
            </div>
            <div>
              <h1 className="text-base sm:text-lg font-black text-white">LEGAL & REGULATORY DISCLAIMER</h1>
              <p className="text-[10px] text-gray-400 font-sans">Official Regulatory Compliance & Operating Statement</p>
            </div>
          </div>
          <Link href="/" className="px-3.5 py-1.5 rounded-xl bg-panel border border-white/10 text-stadiumGreen font-black text-xs hover:bg-stadiumGreen/20 transition-all flex items-center space-x-1">
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Home</span>
          </Link>
        </div>

        {/* Content Box */}
        <div className="glass-panel-premium rounded-3xl border border-white/15 p-5 sm:p-8 space-y-5 text-gray-300 font-sans text-xs leading-relaxed">
          
          <div className="p-4 rounded-2xl bg-black/60 border border-stadiumGreen/40 flex items-start space-x-3">
            <ShieldCheck className="w-5 h-5 text-stadiumGreen flex-shrink-0 mt-0.5" />
            <div>
              <strong className="text-white block font-mono text-xs mb-1">NON-GAMBLING ENTITY DECLARATION:</strong>
              <p className="text-[11px] text-gray-300">
                Mivaj Sports (mivaj.com) is an independent sports statistical intelligence, AI mathematical forecasting, and digital fan media platform. Mivaj is <strong>not a bookmaker</strong>, does not accept bets, does not handle player deposit funds, and does not operate as an unlicensed gambling operator.
              </p>
            </div>
          </div>

          <div className="space-y-2">
            <h2 className="font-mono text-white font-black text-sm">1. Nature of Mathematical Predictions</h2>
            <p>
              All match outcome probabilities, Dixon-Coles Poisson distributions, and confidence ratings generated by Mivaj are purely algorithmic statistical models based on historical form, team ratings, and referee data. Past performance is no guarantee of future match results. Users are solely responsible for their own wagering decisions on third-party licensed platforms.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-mono text-white font-black text-sm">2. Free-to-Play Gamification & Aura Points</h2>
            <p>
              "Aura Points", "Swipe Predictions", and "Fan Banter Challenges" are virtual gamification elements created strictly for fan entertainment and community leaderboard ranking. Aura Points possess zero real-world cash value, cannot be deposited or withdrawn as currency, and do not constitute financial instruments.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-mono text-white font-black text-sm">3. Affiliate Relationship Transparency</h2>
            <p>
              Mivaj Sports participates in affiliate marketing programs with licensed international sportsbooks (e.g. Stake.com, 22Bet). We may receive compensation when users register or engage through affiliate referral links. All affiliate links are clearly denoted.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="font-mono text-white font-black text-sm">4. Age Restriction (18+) & Responsible Play</h2>
            <p>
              This platform is strictly intended for individuals aged 18 and older (or the legal age of majority in your jurisdiction). Sports wagering carries inherent financial risk. If you or someone you know is experiencing gambling-related challenges, please seek professional support.
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-[11px] text-gray-400 flex items-center justify-between flex-wrap gap-2">
            <span>Last Updated: August 2026 &bull; Mivaj Sports &bull; Legal Compliance Office</span>
            <button
              type="button"
              onClick={() => { window.location.href = 'mailto:contact@mivaj.com?subject=Legal%20Compliance%20Inquiry'; }}
              className="text-stadiumGreen font-black hover:underline cursor-pointer bg-transparent border-0 p-0"
            >
              Email Compliance Desk (contact@mivaj.com) ✉️
            </button>
          </div>

        </div>

      </div>
    </div>
  );
}
